services:
  go-server:
    restart: always
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - postgres
      - java-encryption


  java-encryption:
    restart: always
    build:
      context: ./java-encryption
      dockerfile: Dockerfile
    expose:
      - "50051"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    expose:
      - "5432"

